export const AGENT_TOOL_MAP = {
  filesystem: [
    "computer.read_file",
    "computer.write_file",
    "computer.create_directory",
    "computer.list_files",
    "computer.delete_file",
    "computer.organize_files",
  ],
  code: [
    "computer.read_file",
    "computer.write_file",
    "computer.execute_terminal",
  ],
  terminal: [
    "computer.execute_terminal",
  ],
  browser: [
    "computer.open_url",
    "computer.navigate_browser",
    "computer.read_page",
  ],
  "web-search": [
    "computer.navigate_browser",
  ],
  vision: [
    "computer.capture_screen",
    "computer.inspect_screen",
  ],
  camera: [
    "computer.capture_screen",
  ],
  microphone: [
    "computer.inspect_hardware",
  ],
  notifications: [
    "computer.create_notification",
  ],
  media: [
    "computer.control_media",
  ],
  window: [
    "computer.control_window",
  ],
  input: [
    "computer.control_input",
  ],
  hardware: [
    "computer.inspect_hardware",
  ],
  app: [
    "computer.open_app",
    "computer.close_app",
  ],
  system: [
    "computer.system_info",
  ],
  clipboard: [
    "computer.read_file",
    "computer.write_file",
  ],
  download: [
    "computer.navigate_browser",
  ],
  upload: [
    "computer.navigate_browser",
  ],
  search: [
    "computer.navigate_browser",
  ],
};

const CAPABILITY_TO_ABSTRACT = new Map([
  ["System architecture", "system"],
  ["Technical planning", "terminal"],
  ["Product structure", "filesystem"],
  ["Scalability", "system"],
  ["Technical tradeoffs", "system"],
  ["Frontend development", "code"],
  ["Backend development", "code"],
  ["Database design", "code"],
  ["API integration", "code"],
  ["Implementation", "code"],
  ["Refactoring", "code"],
  ["Interface design", "browser"],
  ["Design systems", "code"],
  ["Visual direction", "vision"],
  ["Interaction design", "browser"],
  ["Product aesthetics", "vision"],
  ["Business models", "search"],
  ["Competition analysis", "search"],
  ["Growth strategy", "search"],
  ["Decision making", "terminal"],
  ["Opportunity analysis", "search"],
  ["Content strategy", "browser"],
  ["Brand building", "vision"],
  ["Campaign strategy", "search"],
  ["Audience psychology", "search"],
  ["Growth experiments", "terminal"],
  ["Research", "search"],
  ["Source discovery", "search"],
  ["Summaries", "browser"],
  ["Fact analysis", "search"],
  ["Knowledge synthesis", "search"],
  ["Education", "search"],
  ["Examples", "browser"],
  ["Study plans", "terminal"],
  ["Skill development", "search"],
  ["Concept explanation", "search"],
  ["Writing", "code"],
  ["Storytelling", "code"],
  ["Concept development", "code"],
  ["Creative direction", "vision"],
  ["Ideation", "search"],
  ["Data analysis", "terminal"],
  ["Pattern recognition", "search"],
  ["Reports", "code"],
  ["Optimization", "terminal"],
  ["Metrics", "search"],
  ["Goal setting", "terminal"],
  ["Habits", "terminal"],
  ["Planning", "terminal"],
  ["Accountability", "terminal"],
  ["Progress review", "search"],
  ["Bug isolation", "code"],
  ["Error analysis", "code"],
  ["Root-cause analysis", "terminal"],
  ["Regression prevention", "code"],
  ["React", "code"],
  ["UI implementation", "code"],
  ["Accessibility", "code"],
  ["Performance", "terminal"],
  ["Responsive design", "code"],
  ["APIs", "code"],
  ["Databases", "code"],
  ["Authentication", "code"],
  ["Services", "code"],
  ["Data flows", "code"],
  ["Workflow design", "terminal"],
  ["Triggers", "terminal"],
  ["Integrations", "code"],
  ["Automation", "terminal"],
  ["Scheduling", "terminal"],
  ["Data flow", "code"],
  ["Service contracts", "code"],
  ["API integration", "code"],
  ["Reliability", "terminal"],
  ["Deployment", "terminal"],
  ["CI/CD", "terminal"],
  ["Infrastructure", "terminal"],
  ["Observability", "terminal"],
  ["Recovery", "terminal"],
  ["Schemas", "code"],
  ["SQL", "code"],
  ["Migrations", "code"],
  ["Indexes", "terminal"],
  ["Data lifecycle", "terminal"],
  ["Code review", "code"],
  ["Maintainability", "code"],
  ["Security review", "code"],
  ["Regression detection", "code"],
  ["Threat modeling", "terminal"],
  ["Access control", "code"],
  ["Secret handling", "terminal"],
  ["Security architecture", "terminal"],
  ["Abuse prevention", "terminal"],
  ["Test design", "code"],
  ["Acceptance testing", "code"],
  ["Regression testing", "code"],
  ["Edge cases", "code"],
  ["User journeys", "browser"],
  ["Usability", "browser"],
  ["Information architecture", "browser"],
  ["Interaction analysis", "browser"],
  ["Drafting", "code"],
  ["Editing", "code"],
  ["Voice matching", "code"],
  ["Copywriting", "code"],
  ["Storytelling", "code"],
  ["Proofreading", "code"],
  ["Structure", "code"],
  ["Tone", "code"],
  ["Content formats", "browser"],
  ["Editorial calendars", "terminal"],
  ["Distribution", "browser"],
  ["Media strategy", "browser"],
  ["Visual consistency", "vision"],
  ["Campaign direction", "browser"],
  ["Brand coherence", "vision"],
  ["Brand strategy", "vision"],
  ["Positioning", "vision"],
  ["Voice", "code"],
  ["Visual identity", "vision"],
  ["UI systems", "code"],
  ["Components", "code"],
  ["Visual hierarchy", "browser"],
  ["WCAG", "code"],
  ["Inclusive interaction", "browser"],
  ["Keyboard navigation", "input"],
  ["Assistive technology", "browser"],
  ["Dependencies", "terminal"],
  ["Priorities", "terminal"],
  ["Milestones", "terminal"],
  ["Completion criteria", "terminal"],
  ["Risk planning", "terminal"],
  ["Focus systems", "terminal"],
  ["Prioritization", "terminal"],
  ["Routines", "terminal"],
  ["Time planning", "terminal"],
  ["Scope", "terminal"],
  ["Risks", "terminal"],
  ["Delivery", "terminal"],
  ["Task creation", "terminal"],
  ["Task updates", "terminal"],
  ["Completion tracking", "terminal"],
  ["Calendar management", "browser"],
  ["Availability", "browser"],
  ["Conflict detection", "terminal"],
  ["Reminders", "terminal"],
  ["Timing", "terminal"],
  ["Notification management", "notifications"],
  ["Habit workflows", "terminal"],
  ["Focus missions", "terminal"],
  ["Timers", "terminal"],
  ["Check-ins", "terminal"],
  ["Evidence checks", "search"],
  ["Consistency", "search"],
  ["Result validation", "search"],
  ["Source review", "search"],
  ["Claim checking", "search"],
  ["Uncertainty", "search"],
  ["Evidence quality", "search"],
  ["Taxonomy", "filesystem"],
  ["Connections", "search"],
  ["Knowledge organization", "filesystem"],
  ["Guides", "code"],
  ["API documentation", "code"],
  ["Runbooks", "code"],
  ["Technical writing", "code"],
  ["Data cleaning", "terminal"],
  ["Insights", "search"],
  ["Visualization", "vision"],
  ["Budgeting", "terminal"],
  ["Unit economics", "terminal"],
  ["Financial analysis", "terminal"],
  ["Risk analysis", "terminal"],
  ["Product strategy", "search"],
  ["Roadmaps", "terminal"],
  ["User value", "search"],
  ["Processes", "terminal"],
  ["Capacity", "terminal"],
  ["Operational efficiency", "terminal"],
  ["Computer interaction", "input"],
  ["Application control", "app"],
  ["Input automation", "input"],
  ["Screen interaction", "vision"],
  ["Desktop control", "window"],
  ["Application management", "app"],
  ["Window management", "window"],
  ["System interaction", "system"],
  ["Browser navigation", "browser"],
  ["Page interaction", "browser"],
  ["Form interaction", "browser"],
  ["Web extraction", "browser"],
  ["File discovery", "filesystem"],
  ["Organization", "filesystem"],
  ["Metadata", "filesystem"],
  ["Safe file operations", "filesystem"],
  ["Camera input", "camera"],
  ["Visual analysis", "vision"],
  ["Object recognition", "vision"],
  ["Scene understanding", "vision"],
  ["Notifications", "notifications"],
  ["Priority", "notifications"],
  ["Quiet hours", "notifications"],
  ["Frequency control", "notifications"],
  ["Device handoff", "system"],
  ["Context synchronization", "system"],
  ["Task continuity", "terminal"],
  ["Session transfer", "system"],
  ["Home devices", "hardware"],
  ["Scenes", "hardware"],
  ["Automation", "terminal"],
  ["Wearable data", "hardware"],
  ["Activity signals", "hardware"],
  ["Vehicle information", "hardware"],
  ["Vehicle telemetry", "hardware"],
  ["Approved controls", "input"],
  ["Conversation", "code"],
  ["Follow-ups", "code"],
  ["Dialogue continuity", "code"],
  ["Clarification", "code"],
  ["Translation", "code"],
  ["Localization", "code"],
  ["Tone preservation", "code"],
  ["Context preservation", "code"],
  ["Arabic", "code"],
  ["Kurdish", "code"],
  ["Sorani", "code"],
  ["Kurmanji", "code"],
  ["English", "code"],
  ["Stress recognition", "search"],
  ["Pacing", "terminal"],
  ["Summaries", "browser"],
  ["Key points", "search"],
  ["Action extraction", "terminal"],
  ["Compression", "terminal"],
  ["Speech input", "microphone"],
  ["Speech output", "media"],
  ["Turn-taking", "code"],
  ["Voice interaction", "microphone"],
  ["Web search", "web-search"],
  ["Source collection", "browser"],
  ["Current information", "browser"],
  ["Evidence tracking", "browser"],
  ["Deep research", "web-search"],
  ["Source comparison", "browser"],
  ["Synthesis", "code"],
  ["Uncertainty analysis", "search"],
  ["Source quality", "search"],
  ["Dates", "search"],
  ["Provenance", "search"],
  ["Claim verification", "search"],
  ["Document analysis", "browser"],
  ["Structure extraction", "browser"],
  ["Decision extraction", "search"],
  ["Risk detection", "search"],
  ["PDF reading", "browser"],
  ["PDF extraction", "browser"],
  ["Structure preservation", "browser"],
  ["Research papers", "browser"],
  ["Methods", "browser"],
  ["Literature review", "browser"],
  ["News search", "browser"],
  ["Current events", "browser"],
  ["Timeline analysis", "search"],
  ["Relationships", "search"],
  ["Entity linking", "search"],
  ["Knowledge graphs", "search"],
  ["Context retrieval", "search"],
  ["Validation", "terminal"],
  ["Business models", "search"],
  ["Product-market fit", "search"],
  ["Execution strategy", "terminal"],
  ["Sales", "browser"],
  ["Qualification", "browser"],
  ["Outreach", "browser"],
  ["Follow-up", "terminal"],
  ["Customer research", "browser"],
  ["User needs", "browser"],
  ["Objections", "browser"],
  ["Opportunity discovery", "search"],
  ["Competitor research", "browser"],
  ["Feature comparison", "browser"],
  ["Strategic risks", "search"],
  ["Reflection", "search"],
  ["Decision support", "search"],
  ["Goal systems", "terminal"],
  ["Long-term thinking", "search"],
  ["Lessons", "search"],
  ["Practice", "terminal"],
  ["Learning paths", "search"],
  ["Sleep routines", "terminal"],
  ["Sleep education", "search"],
  ["Stress support", "search"],
  ["Grounding", "terminal"],
  ["Practical next steps", "terminal"],
  ["Movement", "hardware"],
  ["General fitness education", "search"],
  ["Recovery awareness", "search"],
  ["Nutrition education", "search"],
  ["Meal planning", "terminal"],
  ["Food information", "search"],
  ["General healthy habits", "search"],
  ["Agent selection", "system"],
  ["Team formation", "system"],
  ["Delegation", "terminal"],
  ["Handoffs", "system"],
  ["Result synthesis", "code"],
  ["Context", "search"],
  ["Continuity", "search"],
  ["Constraint tracking", "search"],
  ["Session state", "system"],
  ["Intent detection", "search"],
  ["Goal extraction", "search"],
  ["Ambiguity detection", "search"],
  ["Planning", "terminal"],
  ["Error recovery", "terminal"],
  ["Verification", "search"],
  ["Completion checks", "search"],
  ["Failure detection", "search"],
  ["Memory retrieval", "filesystem"],
  ["Memory storage", "filesystem"],
  ["Memory relevance", "search"],
  ["Retention control", "terminal"],
  ["Personality", "code"],
  ["Response style", "code"],
  ["Personalization", "code"],
  ["Quality review", "search"],
  ["Clarity", "search"],
  ["Completeness", "search"],
  ["Authorization", "system"],
  ["Least privilege", "system"],
  ["Risk evaluation", "search"],
  ["Confirmation requirements", "system"],
  ["Audit logs", "system"],
  ["Action history", "system"],
  ["Approval tracking", "system"],
  ["Privacy", "system"],
  ["Data handling", "filesystem"],
  ["Privacy controls", "system"],
  ["Agent generation", "code"],
  ["Capability design", "code"],
  ["Tool mapping", "code"],
  ["Agent validation", "code"],
  ["Workflow creation", "terminal"],
  ["Step orchestration", "terminal"],
  ["Reusable workflows", "terminal"],
  ["Safety assessment", "search"],
  ["De-escalation", "code"],
  ["Trusted support guidance", "search"],
  ["Emergency awareness", "notifications"],
]);

export function getRealToolsForAgent(agent) {
  if (!agent?.tools || !Array.isArray(agent.tools)) return [];
  const toolSet = new Set();
  for (const abstractTool of agent.tools) {
    const realTools = AGENT_TOOL_MAP[abstractTool] || [];
    for (const tool of realTools) toolSet.add(tool);
  }
  return Array.from(toolSet);
}

export function getAllAgentTools(agents) {
  const toolSet = new Set();
  for (const agent of agents) {
    for (const tool of getRealToolsForAgent(agent)) {
      toolSet.add(tool);
    }
  }
  return Array.from(toolSet);
}

export function getToolsForCapabilities(capabilities) {
  if (!Array.isArray(capabilities)) return [];
  const toolSet = new Set();
  for (const cap of capabilities) {
    const abstract = CAPABILITY_TO_ABSTRACT.get(cap);
    if (abstract) {
      const realTools = AGENT_TOOL_MAP[abstract] || [];
      for (const tool of realTools) toolSet.add(tool);
    }
  }
  return Array.from(toolSet);
}

export default {
  AGENT_TOOL_MAP,
  getRealToolsForAgent,
  getAllAgentTools,
  getToolsForCapabilities,
};