const groups = [
  ["Intelligence", [
    ["Intent understanding", "Recognize what the user is trying to accomplish."],
    ["Silent response styles", "Adapt depth, tone, and structure without exposing internal modes."],
    ["Multi-agent collaboration", "Bring the right specialists into a single response."],
    ["Goal decomposition", "Turn a large request into a clear sequence of steps."],
    ["Follow-up awareness", "Understand references to earlier messages and unfinished work."],
    ["Decision support", "Compare options, trade-offs, and likely outcomes."],
    ["Uncertainty detection", "Separate known facts from assumptions and unknowns."],
    ["Personal context", "Use authorized user context to make answers more relevant."],
    ["Conversation repair", "Recover gracefully when a request is ambiguous or misunderstood."],
    ["Answer quality control", "Check clarity, usefulness, privacy, and tone before delivery."],
  ]],
  ["Memory", [
    ["Memory graph", "Connect ideas, people, projects, preferences, and goals."],
    ["Memory confidence", "Track how certain HEY is about remembered information."],
    ["Memory explanations", "Show why a memory was used in a response."],
    ["Memory editing", "Let the user correct or rewrite any remembered fact."],
    ["Memory expiration", "Allow temporary context to fade instead of living forever."],
    ["Preference learning", "Learn stable preferences from explicit user choices."],
    ["Pattern recognition", "Detect recurring routines, friction, and momentum."],
    ["Memory neighborhoods", "Explore related memories around a selected idea."],
    ["Private memory spaces", "Keep sensitive topics separated and permissioned."],
    ["Memory export", "Export, review, or delete the complete personal memory layer."],
  ]],
  ["Execution", [
    ["Action queue", "Turn an intention into a visible, trackable action."],
    ["Permission gates", "Ask before HEY performs sensitive or external actions."],
    ["Undoable actions", "Reverse supported changes instead of leaving the user stuck."],
    ["Audit timeline", "Record what happened, why it happened, and when."],
    ["Workflow runner", "Execute multi-step workflows with dependencies."],
    ["Task dependencies", "Keep blocked tasks from running out of order."],
    ["Retry strategy", "Recover failed steps with bounded retries and alternatives."],
    ["Human approval checkpoints", "Pause high-impact workflows for user confirmation."],
    ["Tool registry", "Give HEY a consistent contract for external tools."],
    ["Device gateway", "Route approved actions to connected devices and services."],
  ]],
  ["Forge", [
    ["Agent builder", "Create specialized intelligence from a plain-language brief."],
    ["Workflow builder", "Design automations visually or conversationally."],
    ["App generator", "Generate a working starting point from an idea."],
    ["Artifact validation", "Inspect generated files for completeness and unsafe content."],
    ["Preview generation", "Create a previewable entry file from a generated artifact."],
    ["Test-and-fix loop", "Run checks, capture errors, and ask HEY to repair the result."],
    ["Version history", "Keep prior Forge versions available for comparison and rollback."],
    ["Template library", "Start from reusable patterns instead of empty canvases."],
    ["Forge marketplace", "Share and discover trusted agents and workflows."],
    ["Deployment handoff", "Move a verified artifact into a chosen hosting workflow."],
  ]],
  ["Research", [
    ["Web research", "Search current information through approved providers."],
    ["Source collection", "Keep research links attached to the answer that used them."],
    ["Source quality ranking", "Prefer authoritative, relevant, and recent sources."],
    ["Claim tracing", "Connect important claims to supporting evidence."],
    ["Product comparison", "Compare options across criteria instead of vibes."],
    ["Document analysis", "Extract useful structure from long documents."],
    ["Research briefs", "Turn scattered findings into a concise decision brief."],
    ["Contradiction detection", "Flag when sources disagree instead of hiding it."],
    ["Citation-ready output", "Format findings for reports, notes, or presentations."],
    ["Research memory", "Save durable findings to the user's knowledge graph."],
  ]],
  ["Life OS", [
    ["Daily briefing", "Start the day with priorities, context, and a realistic plan."],
    ["Focus sessions", "Protect time for deep work with a real session timer."],
    ["Calendar intelligence", "Understand commitments and surface conflicts."],
    ["Goal alignment", "Connect daily actions to longer-term goals."],
    ["Habit momentum", "Track consistency without turning life into punishment."],
    ["Project command", "Keep projects, tasks, notes, and decisions together."],
    ["Journal reflection", "Use writing to discover patterns and next steps."],
    ["Learning paths", "Turn curiosity into a structured, adaptive curriculum."],
    ["Wellbeing check-ins", "Notice strain and suggest supportive adjustments."],
    ["Personal analytics", "Show meaningful trends without exploiting attention."],
  ]],
  ["Voice", [
    ["Natural voice mode", "Talk to HEY without needing to type every request."],
    ["Interruption handling", "Let the user interrupt without losing the thread."],
    ["Voice action confirmation", "Confirm sensitive actions clearly out loud."],
    ["Speaker preference", "Remember the user's preferred voice experience."],
    ["Voice notes", "Turn spoken thoughts into searchable memory."],
    ["Meeting capture", "Capture decisions and action items from approved sessions."],
    ["Read-aloud answers", "Let HEY speak research, plans, and summaries."],
    ["Voice shortcuts", "Trigger frequent workflows with compact phrases."],
    ["Ambient listening control", "Make listening state visible and user-controlled."],
    ["Offline voice queue", "Hold local notes until a connection is available."],
  ]],
  ["Trust", [
    ["Permission center", "See and change what HEY is allowed to access."],
    ["Risk classification", "Classify actions before they are executed."],
    ["Privacy boundaries", "Keep sensitive data out of prompts and generated files."],
    ["Data deletion", "Delete conversations, memories, and generated artifacts."],
    ["Activity receipts", "Explain every external side effect in plain language."],
    ["Safe failure", "Fail closed when a permission or service is unavailable."],
    ["Model routing transparency", "Show useful model and source metadata without clutter."],
    ["Prompt injection defense", "Treat retrieved content as untrusted instructions."],
    ["Crisis safeguards", "Use short, safety-first responses for urgent situations."],
    ["Trust diagnostics", "Run a self-check on permissions, keys, and connections."],
  ]],
  ["Creative", [
    ["Brand studio", "Create a coherent visual identity around an idea."],
    ["Story room", "Develop characters, scenes, and narrative structure."],
    ["Idea constellation", "Generate and connect non-obvious creative directions."],
    ["Writing partner", "Edit for clarity while preserving the user's voice."],
    ["Presentation architect", "Turn a concept into a persuasive presentation flow."],
    ["Content system", "Repurpose one idea into a consistent content series."],
    ["Design critique", "Give practical feedback on hierarchy, rhythm, and usability."],
    ["Mood worlds", "Change visual atmosphere without losing product consistency."],
    ["Creative constraints", "Use deliberate limits to produce stronger ideas."],
    ["Portfolio builder", "Turn projects and proof into a polished personal showcase."],
  ]],
  ["Interface", [
    ["Universal command bar", "Jump to any page, memory, task, or action instantly."],
    ["Scroll storytelling", "Use scroll position as a calm visual narrative."],
    ["Cinematic boot", "Open HEY with a recognizable signature moment."],
    ["Idle screensaver", "Let HEY become a quiet living world when left alone."],
    ["Liquid glass system", "Give controls a consistent responsive material language."],
    ["Theme worlds", "Make each palette feel like a different environment."],
    ["Responsive command layout", "Keep the system useful from phone to desktop."],
    ["Motion accessibility", "Respect reduced-motion preferences everywhere."],
    ["Contextual quick actions", "Surface the most useful next moves in place."],
    ["Capability center", "Give users one place to understand HEY's full surface."],
  ]],
];

export const HEY_FEATURES = groups.flatMap(([category, items]) => items.map(([name, description], index) => ({
  id: `feature-${String(groups.slice(0, groups.findIndex(([group]) => group === category)).reduce((total, [, groupItems]) => total + groupItems.length, 0) + index + 1).padStart(3, "0")}`,
  category,
  name,
  description,
  status: ["Memory graph", "Answer quality control", "Action queue", "Permission gates", "Undoable actions", "Workflow runner", "Tool registry", "Device gateway", "Artifact validation", "Preview generation", "Web research", "Source collection", "Daily briefing", "Focus sessions", "Journal reflection", "Permission center", "Risk classification", "Cinematic boot", "Idle screensaver", "Liquid glass system", "Scroll storytelling"].includes(name) ? "active" : "expanding",
})));

export const FEATURE_CATEGORIES = groups.map(([category]) => category);

export function getFeature(featureId) {
  return HEY_FEATURES.find((feature) => feature.id === featureId) || null;
}

export default HEY_FEATURES;
