/**
 * HEY SURFACE MODES
 * The 24 document modes (MODE-01..24) live on top of the internal
 * intelligence mode registry. Each mode describes a permissioned
 * work surface: what it exists for, what it can touch, and the
 * boundary rule that protects the user.
 */

const MODE_DEFINITIONS = [
  {
    modeId: "MODE-01",
    id: "code",
    name: "Code",
    tagline: "Ship real software from a real workspace.",
    purpose: "Write, run, and iterate on code.",
    keywords: ["code", "program", "script", "bug", "software", "developer"],
    capabilities: ["code.edit", "code.run", "memory.read", "files.write"],
    surfaces: ["workspace", "terminal", "files"],
    states: ["draft", "running", "verified"],
    gates: "Runs only inside the isolated sandbox you see. Nothing touches your filesystem without explicit permission.",
    icon: "Braces",
    color: "gold",
    wb: "code",
  },
  {
    modeId: "MODE-02",
    id: "fix",
    name: "Fix",
    tagline: "Turn a broken thing into a verified repair.",
    purpose: "Diagnose and repair anything with a clear before/after.",
    keywords: ["fix", "repair", "broken", "error", "failed", "restore"],
    capabilities: ["diagnose", "memory.read", "code.edit"],
    surfaces: ["workspace", "steps"],
    states: ["symptom", "hypothesis", "repair", "verified"],
    gates: "A repair is only finished when a verification step proves the fix.",
    icon: "Wrench",
    color: "coral",
    wb: "fix",
  },
  {
    modeId: "MODE-03",
    id: "cowork",
    name: "Cowork",
    tagline: "Two brains, one deliverable, zero silent assumptions.",
    purpose: "Collaborate with HEY on a single mission with visible reasoning.",
    keywords: ["cowork", "together", "collaborate", "mission", "brief", "team"],
    capabilities: ["chat", "memory.read", "plan", "deliver"],
    surfaces: ["chat", "workspace"],
    states: ["brief", "sources", "cross-check", "deliver"],
    gates: "HEY never claims a deliverable is final without an honest cross-check.",
    icon: "Users",
    color: "lavender",
    wb: "cowork",
  },
  {
    modeId: "MODE-04",
    id: "teach",
    name: "Teach",
    tagline: "Learn until it sticks, then prove it.",
    purpose: "Study a topic from sources and graduate through recall practice.",
    keywords: ["teach", "study", "learn", "quiz", "flashcards", "practice", "lesson"],
    capabilities: ["research", "memory.read", "practice"],
    surfaces: ["workspace", "steps"],
    states: ["topic", "studying", "practicing", "graduated"],
    gates: "Study-only mode. Progress is honest: you graduate by recall, not by hours.",
    icon: "GraduationCap",
    color: "green",
    wb: "teach",
  },
  {
    modeId: "MODE-05",
    id: "research",
    name: "Research",
    tagline: "Claims need receipts.",
    purpose: "Gather evidence and keep every important claim traceable.",
    keywords: ["research", "search", "source", "evidence", "facts", "investigate"],
    capabilities: ["web.search", "research", "memory.read"],
    surfaces: ["workspace", "sources"],
    states: ["question", "collecting", "attributing", "finished"],
    gates: "Every important claim is attached to a source. No source, no claim.",
    icon: "Search",
    color: "lavender",
    wb: "research",
  },
  {
    modeId: "MODE-06",
    id: "create",
    name: "Create",
    tagline: "From a spark to a thing you can keep.",
    purpose: "Generate, shape, and refine original artifacts.",
    keywords: ["create", "generate", "idea", "draft", "invent", "make", "imagine"],
    capabilities: ["generate", "memory.read", "artifact.write"],
    surfaces: ["workspace"],
    states: ["spark", "exploring", "shaping", "artifact"],
    gates: "Generated work is labeled as generated, never silently passed off.",
    icon: "Sparkles",
    color: "gold",
    wb: "create",
  },
  {
    modeId: "MODE-07",
    id: "write",
    name: "Write",
    tagline: "Say exactly what you mean.",
    purpose: "Draft, rewrite, and polish writing with versions you can compare.",
    keywords: ["write", "draft", "essay", "email", "story", "rewrite", "polish"],
    capabilities: ["generate", "memory.read"],
    surfaces: ["workspace"],
    states: ["draft", "version", "polished"],
    gates: "Every rewrite keeps the previous version. You can always go back.",
    icon: "Feather",
    color: "lavender",
    wb: "write",
  },
  {
    modeId: "MODE-08",
    id: "design",
    name: "Design",
    tagline: "Make it feel the way you intend.",
    purpose: "Prototype and shape visual direction.",
    keywords: ["design", "ui", "ux", "visual", "style", "palette", "layout"],
    capabilities: ["generate", "prototype"],
    surfaces: ["workspace", "preview"],
    states: ["brief", "direction", "prototype"],
    gates: "Designs ship as prototypes until you approve the direction.",
    icon: "PenTool",
    color: "green",
    wb: "design",
  },
  {
    modeId: "MODE-09",
    id: "analyze",
    name: "Analyze",
    tagline: "Put numbers to the question.",
    purpose: "Analyze data with auditable formulas and plain-language findings.",
    keywords: ["analyze", "data", "numbers", "stats", "trend", "measure", "formula"],
    capabilities: ["compute", "memory.read"],
    surfaces: ["workspace", "data"],
    states: ["data", "model", "finding"],
    gates: "Every number shown can be traced to its formula.",
    icon: "BarChart3",
    color: "coral",
    wb: "analyze",
  },
  {
    modeId: "MODE-10",
    id: "organize",
    name: "Organize",
    tagline: "Everything has one home.",
    purpose: "Capture scraps and place them where they belong.",
    keywords: ["organize", "sort", "file", "inbox", "folders", "declutter", "label"],
    capabilities: ["memory.read", "memory.write"],
    surfaces: ["workspace", "inbox"],
    states: ["inbox", "sorting", "filing", "verified"],
    gates: "Nothing is silently archived. Sorting is a visible, confirmed step.",
    icon: "FolderKanban",
    color: "lavender",
    wb: "organize",
  },
  {
    modeId: "MODE-11",
    id: "automate",
    name: "Automate",
    tagline: "Let the machine do the repeatable part.",
    purpose: "Design automations that free you from repetition.",
    keywords: ["automate", "workflow", "trigger", "schedule", "repeat", "macro"],
    capabilities: ["workflow", "memory.read"],
    surfaces: ["workspace", "steps"],
    states: ["idea", "simulate", "install", "off"],
    gates: "An automation always has an off switch and runs on permission.",
    icon: "Workflow",
    color: "gold",
    wb: "automate",
  },
  {
    modeId: "MODE-12",
    id: "present",
    name: "Present",
    tagline: "Make the room understand.",
    purpose: "Turn a concept into a persuasive, well-paced presentation.",
    keywords: ["present", "slides", "talk", "deck", "pitch", "presentation"],
    capabilities: ["generate", "preview"],
    surfaces: ["workspace", "preview"],
    states: ["message", "structure", "slides"],
    gates: "Presenter view respects your pace; nothing advances on its own.",
    icon: "MonitorUp",
    color: "coral",
    wb: "present",
  },
  {
    modeId: "MODE-13",
    id: "meet",
    name: "Meet",
    tagline: "Never lose the thread of a meeting.",
    purpose: "Capture, organize, and follow up on conversations.",
    keywords: ["meet", "meeting", "notes", "agenda", "minutes", "session"],
    capabilities: ["microphone", "memory.write"],
    surfaces: ["workspace", "transcript"],
    states: ["agenda", "live", "review", "followup"],
    gates: "The microphone is gated: transcription starts only when you say so.",
    icon: "Mic",
    color: "green",
    wb: "meet",
  },
  {
    modeId: "MODE-14",
    id: "plan",
    name: "Plan",
    tagline: "Decide with your eyes open.",
    purpose: "Compare options and build a plan someone can actually follow.",
    keywords: ["plan", "planning", "options", "decide", "steps", "timeline", "strategy"],
    capabilities: ["research", "plan", "memory.read"],
    surfaces: ["workspace", "steps"],
    states: ["goal", "options", "criteria", "plan"],
    gates: "Every plan shows its options, criteria, and who is responsible.",
    icon: "Route",
    color: "lavender",
    wb: "plan",
  },
  {
    modeId: "MODE-15",
    id: "review",
    name: "Review",
    tagline: "Second eyes on everything that matters.",
    purpose: "Check work against evidence with a fair appeal process.",
    keywords: ["review", "check", "verify", "audit", "approve", "critique"],
    capabilities: ["research", "memory.read", "audit"],
    surfaces: ["workspace", "checks"],
    states: ["items", "evidence", "verdict", "appeal"],
    gates: "A failed check can always be appealed with new evidence.",
    icon: "ShieldCheck",
    color: "gold",
    wb: "review",
  },
  {
    modeId: "MODE-16",
    id: "focus",
    name: "Focus",
    tagline: "Protect the next twenty minutes.",
    purpose: "Run focused sessions with a real timer and honest boundaries.",
    keywords: ["focus", "timer", "session", "deep work", "pomodoro", "distraction"],
    capabilities: ["timer", "notifications", "memory.read"],
    surfaces: ["workspace", "timer"],
    states: ["ready", "running", "done"],
    gates: "Focus protects your time; it never claims to block the internet for you.",
    icon: "Clock3",
    color: "green",
    wb: "focus",
  },
  {
    modeId: "MODE-17",
    id: "explore",
    name: "Explore",
    tagline: "Follow curiosity somewhere new.",
    purpose: "Discover new ideas and surprising connections.",
    keywords: ["explore", "discover", "curious", "wonder", "learn", "wander"],
    capabilities: ["research", "generate"],
    surfaces: ["workspace", "sparks"],
    states: ["seed", "radar", "paths"],
    gates: "Exploration follows your seed; it never redirects to a sales agenda.",
    icon: "Compass",
    color: "coral",
    wb: "explore",
  },
  {
    modeId: "MODE-18",
    id: "translate",
    name: "Translate",
    tagline: "Say it in the other language too.",
    purpose: "Translate with a working glossary so terms stay consistent.",
    keywords: ["translate", "language", "glossary", "localize", "عربي", "كوردى"],
    capabilities: ["generate", "memory.read"],
    surfaces: ["workspace"],
    states: ["source", "glossary", "translation"],
    gates: "Translations show their source text and honor the glossary you set.",
    icon: "Languages",
    color: "lavender",
    wb: "translate",
  },
  {
    modeId: "MODE-19",
    id: "remember",
    name: "Remember",
    tagline: "So HEY actually remembers.",
    purpose: "Deposit memories into the Cosmos and retrieve them by need.",
    keywords: ["remember", "memory", "recall", "fact", "save", "forget", "cosmos"],
    capabilities: ["memory.write", "memory.read"],
    surfaces: ["workspace", "memory"],
    states: ["capture", "classify", "retrieve"],
    gates: "Memories are tagged with source, scope, and expiry. Nothing is assumed permanent.",
    icon: "Brain",
    color: "gold",
    wb: "remember",
  },
  {
    modeId: "MODE-20",
    id: "home",
    name: "Home",
    tagline: "The calm start of every session.",
    purpose: "A truthful surface that shows where you left off.",
    keywords: ["home", "start", "overview", "today", "morning"],
    capabilities: ["memory.read", "task.read"],
    surfaces: ["home"],
    states: ["idle", "brief"],
    gates: "Home reports what is true. It does not invent status.",
    icon: "House",
    color: "lavender",
    wb: "home",
  },
  {
    modeId: "MODE-21",
    id: "access",
    name: "Access",
    tagline: "Make the whole HEY easier to see.",
    purpose: "Adjust how HEY looks and behaves for your needs.",
    keywords: ["access", "accessibility", "contrast", "text", "motion", "font", "reader"],
    capabilities: ["presentation"],
    surfaces: ["workspace", "system"],
    states: ["inspecting", "adjusting", "saved"],
    gates: "Every access change is reversible and applied only after your confirmation.",
    icon: "Accessibility",
    color: "coral",
    wb: "access",
  },
  {
    modeId: "MODE-22",
    id: "operate",
    name: "Operate",
    tagline: "Touch anything, only with permission.",
    purpose: "Give HEY access to device capability — always gated.",
    keywords: ["operate", "device", "hardware", "phone", "camera", "screen", "location", "permission"],
    capabilities: ["device.*"],
    surfaces: ["workspace", "devices"],
    states: ["request", "granted", "performing"],
    gates: "Every capability is permission-gated. HEY asks before it touches anything.",
    icon: "Smartphone",
    color: "gold",
    wb: "operate",
  },
  {
    modeId: "MODE-23",
    id: "personal",
    name: "Personal",
    tagline: "One thing, held honestly.",
    purpose: "A private space for whatever matters most right now.",
    keywords: ["personal", "private", "journal", "one thing", "next action"],
    capabilities: ["memory.write", "memory.read"],
    surfaces: ["workspace"],
    states: ["focus", "journal", "next"],
    gates: "This surface keeps your private content inside your account.",
    icon: "Heart",
    color: "green",
    wb: "personal",
  },
  {
    modeId: "MODE-24",
    id: "custom",
    name: "Custom",
    tagline: "Design your own mode.",
    purpose: "Assemble a new mode from capabilities and a purpose.",
    keywords: ["custom", "build", "own", "create-mode", "define"],
    capabilities: ["registry.write"],
    surfaces: ["workspace", "studio"],
    states: ["brief", "assemble", "saved"],
    gates: "Custom modes inherit the same permission rules as every other mode.",
    icon: "Spline",
    color: "lavender",
    wb: "custom",
  },
];

export const SURFACE_MODES = MODE_DEFINITIONS;

const CUSTOM_KEY = "hey_surface_custom_modes";

export function loadCustomModes() {
  try {
    const raw = localStorage.getItem(CUSTOM_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter((mode) => mode?.id && mode?.name) : [];
  } catch {
    return [];
  }
}

export function saveCustomModes(modes) {
  try {
    localStorage.setItem(CUSTOM_KEY, JSON.stringify(modes));
    return true;
  } catch {
    return false;
  }
}

export function allSurfaceModes() {
  return [...SURFACE_MODES, ...loadCustomModes()];
}

export function getSurfaceMode(modeId) {
  if (modeId === "auto") return { ...SURFACE_MODES[0], id: "auto", modeId: "AUTO", name: "Auto", wb: "auto" };
  const all = allSurfaceModes();
  return all.find((mode) => mode.id === modeId) || null;
}

export function findSurfaceModeByKeyword(text) {
  const query = String(text || "").toLowerCase();
  const all = allSurfaceModes();
  const direct = all.find((mode) => mode.id === query || String(mode.modeId).toLowerCase() === query);
  if (direct) return direct;
  return all.find((mode) =>
    [mode.name, mode.purpose, ...(mode.keywords || [])].some((term) =>
      String(term).toLowerCase().split(" ").some((word) => word && query.includes(word)),
    ),
  ) || null;
}

export default {
  modes: SURFACE_MODES,
  all: allSurfaceModes,
  get: getSurfaceMode,
  find: findSurfaceModeByKeyword,
  loadCustom: loadCustomModes,
  saveCustom: saveCustomModes,
};